name: grz-upload-client
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.12
  - typing-extensions
  - boto3
  - pyyaml
  - click
  - python-crypt4gh
  - tqdm
  - jsonschema
  - pydantic >=2.9.2
