name: grz-upload-client-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - boto3
  - pyyaml
  - click
  - python-crypt4gh
  - tqdm
  - jsonschema
  # packages required for development
  - pytest
  - pytest-mock
  - moto
  - numpy
