name: grz-upload-client-dev
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python >=3.12
  - boto3 >=1.35.39,<2
  - pyyaml >=6.0.2,<7
  - click >=8.1.7,<9
  - python-crypt4gh >=1.7,<2
  - tqdm >=4.66.5,<5
  - jsonschema >=4.23.0,<5
  - pydantic >=2.9.2,<2.10
  - platformdirs >=4.3.6,<5
  # packages required for development
  - pytest >=8.3.3,<9
  - pytest-cov >=5.0.0,<6
  - pytest-mock >=3.14.0,<4
  - pytest-sugar >=1.0.0,<2
  - moto >=5.0.16,<6
  - numpy >=2.1.2,<3
  - mypy >=1.13.0,<2
  # - tox >=4.23.2,<5  # install via `uv tool install tox --with tox-uv` instead
  - ruff >=0.9.6,<1
  - uv >=0.5.5,<1
