name: grz-upload-client
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python >=3.12
  - boto3 =1.35.39
  - pyyaml =6.0.2
  - click =8.1.7
  - python-crypt4gh =1.7
  - tqdm =4.66.5
  - jsonschema =4.23.0
  - pydantic =2.9.2
